spring:
    application:
        name: Prueba Tecnica User - BCI
        
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
            
        log-request-details: true
            
    h2:
       console:
            enabled: true

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:userdb
        username: user
        password: pass
        hikari:
            maximum-pool-size: 2

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

    security:
        user:
           name: user
           
           password: bcitest

logging:
    level:
       org:
         springframework:
            web: 
              filter:
                CommonsRequestLoggingFilter: DEBUG
         hibernate: ERROR

server:
    port: 8080

springdoc:
    swagger-ui:
        operations-sorter: alpha
        tags-sorter: alpha
    paths-to-exclude: /error
    
user:
    email: ^([0-9a-zA-Z]+[-._+&])*[0-9a-zA-Z]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}$
    
    pass: ^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&-+=()]).{8,10}$

jwt:
  secret: YOUR_SECRET_KEY
  expiration: 86400000